### ISSUE TITLE
FR: Add video/webm support.

### ISSUE THREAD

**Issue by l-const** [pop-os/cosmic-player#19]
VLC appears to support it.

**Comment by Quackdoc** [comment]
Cosmic-player supports webms, it's more likely that the specific codec the video is encoded in is not compatible with the current setup. Can you install mediainfo from your distro's repo and run `mediainfo  video.webm` and send the output?

**Comment by l-const** [comment]
Thnx, I think I probably didn't have all the plugins installed at that point in time. Closing.
