### ISSUE TITLE
Please add Hardware Accelerated Decoding

### ISSUE THREAD

**Issue by sonicrules1234** [pop-os/cosmic-player#21]
When playing videos that use the av1 codec for video, I'm getting some lag/skipped frames.

**Comment by jackpot51** [comment]
cosmic-player uses vaapi when it is available. Please check that your GPU and drivers support it.

**Comment by sonicrules1234** [comment]
It does, and it was working fine with the ffmpeg version of cosmic-player.  Also, I have the gstreamer-vaapi package installed.  I'm on arch linux.

**Comment by sonicrules1234** [comment]
Looking into it, according to [https://gstreamer.freedesktop.org/documentation/tutorials/playback/hardware-accelerated-video-decoding.html?gi-language=c](https://gstreamer.freedesktop.org/documentation/tutorials/playback/hardware-accelerated-video-decoding.html?gi-language=c), playbin may choose software decoders over hardware ones, depending on their rank.
There's also a note that says: "The GStreamer developers often rank hardware decoders lower than the software ones when they are defective. This should act as a warning."
I found that forcing vaapidecodebin into the pipeline makes av1 play smoothly for me.

**Comment by Quackdoc** [comment]
can you try using `gst-plugin-va` instead of `gstreamer-vaapi`?

gst-plugins-vaapi or gstreamer-vaapi are inferior and now older plugins that have taken a backseat to the va plugins. I just went back and verified that cosmic-player will use vaapi when I have va installed but not when I just use vaapi.

**Comment by sonicrules1234** [comment]
Looks like that fixed it.  Thanks for the help
